//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FreeOTFE4PDA.rc
//
#define IDD_MOUNT_BASIC                 102
#define IDD_ABOUT                       105
#define ID_HELP_ABOUT                   106
#define ID_FILE_EXIT                    107
#define IDI_ICON1                       108
#define IDI_ICON_MAIN                   109
#define IDR_TOOLBAR_MAIN                110
#define IDR_MENU_DONECANCEL             114
#define IDD_MOUNT_ADV                   116
#define IDD_VOL_ADV_OPTS                116
#define IDI_ICON_MAIN_SMALL             117
#define IDR_MENU_CONTEXT                118
#define IDD_PROPERTIES                  120
#define IDD_NEWVOLWIZARD_SUMMARY        121
#define IDD_NEWVOLWIZARD_FILENAME       122
#define IDD_FILENAME                    122
#define IDR_MENU_WIZARD                 122
#define IDD_NEWVOLWIZARD_MASTERKEYLEN   123
#define IDR_MENU_MAIN1                  123
#define IDR_MENU_MAIN_DEBUG             123
#define IDD_NEWVOLWIZARD_HASHCYPHERIV   124
#define IDS_STRING_WELCOME              124
#define IDD_NEWVOLWIZARD_CDBLOCATION    125
#define IDS_STRING_INSTR_FILENAME       125
#define IDD_NEWVOLWIZARD_SALT           126
#define IDS_STRING_INSTR_OFFSET         126
#define IDD_NEWVOLWIZARD_PASSWORD       127
#define IDS_STRING_INSTR_SIZE           127
#define IDD_NEWVOLWIZARD_RNGSELECT      128
#define IDS_STRING_INSTR_HASHCYPHERIV   128
#define IDD_RNGSELECT                   128
#define IDD_NEWVOLWIZARD_RNGMOUSEMOVEMENT 129
#define IDS_STRING_INSTR_MASTERKEYLEN   129
#define IDD_RNGMOUSEMOVEMENT            129
#define IDS_STRING_INSTR_RNGSELECT      130
#define IDD_NEWVOLWIZARD_OFFSET         131
#define IDS_STRING_INSTR_RNGMOUSEMOVEMENT 131
#define IDD_NEWVOLWIZARD_SIZE           132
#define IDS_STRING_INSTR_PASSWORD       132
#define IDD_NEWVOLWIZARD_WELCOME        133
#define IDS_STRING_INSTR_SALT           133
#define IDD_WIZARD_WELCOME              133
#define IDS_STRING_INSTR_CDBLOCATION    134
#define IDD_BACKUPRESTORE               134
#define IDS_STRING_WIZTITLE_NEWVOL      135
#define IDS_STRING_WIZTITLE_CHPASS      136
#define IDS_STRING_WIZTITLE_NEWKEYFILE  137
#define IDS_STRING_WIZDESC_NEWVOL       138
#define IDS_STRING_WIZDESC_CHPASS       139
#define IDS_STRING_WIZDESC_NEWKEYFILE   140
#define IDS_STRING_STATS_WARNING        141
#define IDS_STRING_INSTWIZDUMPCDBPASSWORD 141
#define IDD_DIALOG_TAB                  142
#define IDS_STRING_INSTWIZCHPASS_SRCFILE 142
#define IDS_STRING_INSTWIZNEWKEYFILE_SRCFILE 143
#define IDS_STRING_INSTWIZCHPASS_SRCPASSWORD 144
#define IDS_STRING_INSTWIZNEWKEYFILE_SRCPASSWORD 145
#define IDS_STRING_INSTWIZNEWKEYFILE_DESTFILE 146
#define IDD_OPTIONS                     146
#define IDD_OPTIONS_GENERAL_ONE         146
#define IDS_STRING_INSTWIZCHPASS_DESTPASSWORD 147
#define IDR_MENU_LEFTRIGHT              147
#define IDR_MENU_DUMMY_LEFTRIGHT        147
#define IDD_NEWVOLWIZARD_SIZE1          147
#define IDD_NEWVOLWIZARD_INSTRUCTONLY   147
#define IDS_STRING_INSTWIZNEWKEYFILE_DESTPASSWORD 148
#define IDR_MENU1                       148
#define IDR_MENU_EMPTY                  148
#define IDR_MENU_WIZARD_SOFTKEY         148
#define IDD_OPTIONS_HASHES              148
#define IDS_STRING_INSTWIZNEWKEYFILE_RNGSELECT 149
#define IDR_MENU_MAIN_SOFTKEY           149
#define IDD_OPTIONS_GENERAL_TWO         149
#define IDS_STRING_INSTWIZCHPASS_RNGSELECT 150
#define IDD_OPTIONS_HASHES1             150
#define IDD_OPTIONS_CYPHERS             150
#define IDS_STRING_INST_DUMPCDB_DESTFILE 151
#define IDD_MOUNTLUKS_ADV               151
#define IDD_VOL_ADV_OPTS_LUKS           151
#define IDS_STRING_INST_DUMPCDB_SRCFILE 152
#define IDD_MOUNTLUKS_BASIC             152
#define IDS_STRING_INSTR_READYFORNEWVOL_DESC 153
#define IDD_TRANSLATION                 153
#define IDS_STRING_INSTR_READYFORNEWVOL_TITLE 154
#define IDD_NEWVOLWIZARD_KEYITERATIONS  154
#define IDS_STRING_INST_DUMPLUKS_DESTFILE 155
#define IDD_INFO_CYPHER_DRIVER          155
#define IDS_STRING_INST_DUMPLUKS_SRCFILE 156
#define IDD_INFO_CYPHER_IMPLEMENTATION  156
#define IDS_STRING_INSTWIZDUMPLUKSPASSWORD 157
#define IDD_INFO_HASH_IMPLEMENTATION    157
#define IDS_STRING158                   158
#define IDS_STRING_INSTR_KEYITERATIONS  158
#define IDD_INFO_HASH_DRIVER            158
#define IDC_EDIT_FILENAME               1002
#define IDC_EDIT_MOUNTPOINT             1003
#define IDC_SPIN_SALTLENGTH             1004
#define IDC_APP_TITLE                   1007
#define IDC_APP_VERSION                 1008
#define IDC_EDIT_SIZE                   1009
#define IDC_CHECK_READONLY              1010
#define IDC_BUTTON_BROWSE               1011
#define IDC_EDIT_PASSWORD               1012
#define IDC_EDIT_PASSWORDCONFIRM        1013
#define IDC_BUTTON_TEST_1               1014
#define IDC_BUTTON2                     1015
#define IDC_BUTTON_TEST_2               1016
#define IDC_EDIT_KEYFILE                1017
#define IDC_SPIN_KEYITERATIONS          1018
#define IDC_EDIT_SALTLENGTH             1019
#define IDC_EDIT_KEYITERATIONS          1020
#define IDC_SPIN_OFFSET                 1021
#define IDC_EDIT_OFFSET                 1022
#define IDC_CHECK_CDBATOFFSET           1023
#define IDC_EDIT_DESTOFFSET             1023
#define IDC_BUTTON_BROWSEKEYFILE        1024
#define IDC_SPIN_OFFSET2                1025
#define IDC_SPIN_DESTOFFSET             1025
#define IDC_BUTTON_BROWSEFILENAME       1026
#define IDC_DRIVER_VERSION              1027
#define IDC_EDIT_PROP_VOLUME            1029
#define IDC_EDIT_PROP_MOUNTEDFOR        1030
#define IDC_EDIT_PROP_SECTOR_IVS        1032
#define IDC_EDIT_PROP_CYPHER_IV         1033
#define IDC_EDIT_PROP_HASH_IV           1036
#define IDC_EDIT_PROP_CYPHER_MAIN       1037
#define IDC_EDIT_PROP_DEVICE            1038
#define IDC_EDIT_PROP_DEVICENAME        1038
#define IDC_EDIT_PROP_MOUNTPOINT        1039
#define IDC_LIST1                       1040
#define IDC_LIST_DRIVERS                1040
#define IDC_CHECK_VOLUMEIV              1041
#define IDC_COMBO_HASH                  1042
#define IDC_COMBO_CYPHER                1043
#define IDC_COMBO_SECTORIV              1044
#define IDC_EDIT_MASTERKEYLEN           1045
#define IDC_RADIO_CDBINVOLUME           1048
#define IDC_RADIO_CDBINKEYFILE          1049
#define IDC_SPIN_MASTERKEYLEN           1050
#define IDC_STATIC_KEYFILE              1053
#define IDC_EDIT_SUMMARY                1056
#define IDC_CHECK_RNGMSCRYPTOAPI        1057
#define IDC_CHECK_RNGUSERINPUT          1058
#define IDC_STATIC_WELCOME_TITLE        1059
#define IDC_STATIC_WELCOME_BLOCK_1      1060
#define IDC_STATIC_WELCOME              1060
#define IDC_STATIC_WELCOME_DESC         1060
#define IDC_STATIC_WELCOME_BLOCK_2      1061
#define IDC_STATIC_WELCOME_BLOCK_3      1062
#define IDC_STATIC_WELCOME_NEXT         1062
#define IDC_STATIC_INSTRUCTION          1063
#define IDC_STATIC_URL                  1064
#define IDC_APP_AUTHORCREDIT            1065
#define IDC_STATIC_WARNING_BLOCK_2      1066
#define IDC_APP_AUTHORCREDIT2           1066
#define IDC_APP_TRANSLATORCREDIT        1066
#define IDC_STATIC_WARNING_BLOCK_1      1067
#define IDC_STATIC_FILENAME             1068
#define IDC_TAB1                        1069
#define IDC_STATIC_PASSWORDCONFIRM      1070
#define IDC_STATIC_USERRNG_REQUIRED     1071
#define IDC_STATIC_USERRNG_STORED       1072
#define IDC_STATIC_USERRNGPLACEHOLDER   1073
#define IDC_GROUP_SRC                   1074
#define IDC_GROUP_DEST                  1075
#define IDC_STATIC_SRCFILENAME          1076
#define IDC_STATIC_SRCOFFSET            1077
#define IDC_STATIC_DESTFILENAME         1078
#define IDC_STATIC_DESTOFFSET           1079
#define IDC_EDIT_SRCFILENAME            1080
#define IDC_EDIT_DESTFILENAME           1081
#define IDC_BUTTON_BROWSESRCFILE        1082
#define IDC_EDIT_SRCOFFSET              1083
#define IDC_SPIN_SRCOFFSET              1084
#define IDC_BUTTON_BROWSEDESTFILE       1085
#define IDC_CHECK1                      1087
#define IDC_CHECK_SAVESETTINGS          1087
#define IDC_CHECK_WELCOME_OPTION        1087
#define IDC_CHECK_AUTOMOUNTAFTERCREATE  1087
#define IDC_CHECK_ASSOCIATE             1089
#define IDC_RADIO_MNTPNT_DEFAULT        1092
#define IDC_RADIO_MNTPNT_VOL            1093
#define IDC_EDIT_EXPLORER               1094
#define IDC_BUTTON_BROWSEEXPLORER       1095
#define IDC_STATIC_MOUNTPOINT           1096
#define IDC_CHECK2                      1097
#define IDC_CHECK_EXPLOREONMOUNT        1097
#define IDC_CHECK3                      1098
#define IDC_CHECK_LARGEICONS            1098
#define IDC_CHECK_SOFTKEYMENUS          1099
#define IDC_STATIC_ICON                 1099
#define IDC_STATIC_LABEL_DRIVER_VERSION 1100
#define IDC_CHECK_REVERTVOLTIMESTAMPS   1101
#define IDC_STATIC_HASH                 1102
#define IDC_STATIC_CYPHER               1103
#define IDC_STATIC_VOLUMEIV             1104
#define IDC_STATIC_SECTORIV             1104
#define IDC_STATIC_CNT_SELECTED         1105
#define IDC_EDIT_SIZELIMIT              1106
#define IDC_CHECK_BASEIVCYPHERONHASHLENGTH 1107
#define IDC_SPIN_SIZELIMIT              1108
#define IDC_STATIC_SIZELIMIT            1109
#define IDC_STATIC_SIZELIMITBYTES       1110
#define IDC_COMBO_LANGUAGE              1111
#define IDC_STATIC_USERRNG_STORED_GENERATED 1112
#define IDC_STATIC_USERRNG_GENERATED_REQUIRED 1112
#define IDC_EDIT_TRANSLATE_NAME         1117
#define IDC_EDIT_TRANSLATE_LANG_NAME    1117
#define IDC_EDIT_TRANSLATE_NAME2        1118
#define IDC_BUTTON1                     1118
#define IDC_BUTTON_LANG_DETAILS         1118
#define IDC_EDIT_TRANSLATE_LANG_CODE    1118
#define IDC_BUTTON_CYPHERINFO_MAIN      1118
#define IDC_EDIT_TRANSLATE_NAME3        1119
#define IDC_EDIT_TRANSLATE_TRANSLATOR   1119
#define IDC_EDIT_CYPHER_DRIVER_FILENAME 1119
#define IDC_BUTTON_HASHINFO_IV          1119
#define IDC_EDIT_CYPHER_DRIVER_GUID     1120
#define IDC_BUTTON_CYPHERINFO_IV        1120
#define IDC_EDIT_CYPHER_DRIVER_TITLE    1121
#define IDC_EDIT_CYPHER_DRIVER_VERSION  1122
#define IDC_EDIT_CYPHER_DRIVER_CYPHERCOUNT 1123
#define IDC_EDIT_CYPHER_IMPLEMENTATION_VERSION 1124
#define IDC_EDIT_CYPHER_IMPLEMENTATION_GUID 1125
#define IDC_EDIT_CYPHER_IMPLEMENTATION_TITLE 1126
#define IDC_EDIT_CYPHER_IMPLEMENTATION_MODE 1127
#define IDC_EDIT_CYPHER_IMPLEMENTATION_KEYSIZE 1128
#define IDC_EDIT_CYPHER_IMPLEMENTATION_BLOCKSIZE 1129
#define IDC_EDIT_HASH_DRIVER_GUID       1130
#define IDC_EDIT_HASH_DRIVER_FILENAME   1131
#define IDC_EDIT_HASH_DRIVER_TITLE      1132
#define IDC_EDIT_HASH_DRIVER_VERSION    1133
#define IDC_EDIT_HASH_DRIVER_HASHCOUNT  1134
#define IDC_EDIT_HASH_IMPLEMENTATION_GUID 1135
#define IDC_EDIT_HASH_IMPLEMENTATION_TITLE 1136
#define IDC_EDIT_HASH_IMPLEMENTATION_VERSION 1137
#define IDC_EDIT_HASH_IMPLEMENTATION_KEYSIZE 1138
#define IDC_EDIT_HASH_IMPLEMENTATION_LENGTH 1138
#define IDC_EDIT_HASH_IMPLEMENTATION_BLOCKSIZE 1139
#define IDC_BUTTON_CYPHERINFO           1140
#define IDC_BUTTON_HASHINFO             1141
#define IDC_STATIC_DESTOFFSETBYTES      1142
#define IDC_STATIC_SRCOFFSETBYTES       1143
#define ID_VIEW_REFRESH                 40001
#define ID_FILE_NEWVOL                  40008
#define ID_FILE_MOUNT                   40009
#define ID_FILE_DISMOUNT                40010
#define ID_FILE_DISMOUNTALL             40011
#define ID_CANCEL_TEST                  40015
#define ID_EREER_ERER                   40016
#define ID_EREER                        40017
#define ID_CANCEL                       40018
#define ID_DONE                         40019
#define IDR_MENU_MAIN                   40020
#define ID_TEST_TEST1                   40021
#define ID_TEST_TEST2                   40022
#define ID_TEST_TEST_XXX_1              40023
#define ID_TEST_TEST_XXX_2              40024
#define ID_TEST_TEST3                   40025
#define ID_TEST_TEST_XXX_3              40026
#define IDC_SPIN_SIZE                   40027
#define ID_VIEW_PROPERTIES              40027
#define ID_CONTEXTMENU_PROPERTIES       40028
#define ID_WIZARD_BACK                  40029
#define ID_WIZARD_NEXT                  40030
#define ID_WIZARD_FINISH                40031
#define ID_WIZ_NEXT                     40032
#define ID_WIZ_BACJ                     40033
#define ID_WIZ_BACK                     40034
#define ID_TOOLS_CREATEKEYFILE          40035
#define ID_TOOLS_CHANGEVOLUME           40036
#define ID_TOOLS_CHANGEDETAILS          40037
#define ID_TOOLS_CHANGEPASSWORD         40038
#define ID_Menu                         40039
#define ID_TEST_CYPHER                  40040
#define ID_STATS_CYPHER                 40041
#define ID_STATS_REPORT                 40042
#define ID_TOOLS_CRITICALDATABLOCK      40043
#define ID_CRITICALDATABLOCK_DUMPTOHUMANREADABLEFILE 40044
#define ID_TOOLS_CDBDUMP                40045
#define ID_CRITICALDATABLOCK_BACKUP     40046
#define ID_CRITICALDATABLOCK_RESTORE    40047
#define ID_TOOLS_CDBRESTORE             40048
#define ID_TOOLS_CDBBACKUP              40049
#define ID_VIEW_OPTIONS                 40050
#define ID_CONTEXTMENU_EXPLORER         40051
#define ID_CONTEXTMENU_EXPLORE          40052
#define ID_LEFTITEM                     40055
#define ID_SOFTKEY_RIGHT                40056
#define ID_SOFTKEY_LEFT                 40057
#define ID_SSS                          40061
#define ID_QQQ                          40062
#define ID_HELP_USERGUIDE               40063
#define ID_HELP_DOCUMENTATION           40064
#define ID_                             40065
#define ID_EXIT                         40066
#define ID_FILE_LINUX                   40067
#define ID_LINUX_MOUNT                  40068
#define ID_FILE_MOUNT_LINUX             40069
#define ID_LINUX_FRED                   40070
#define ID_LINUX_LUKSDUMP               40071

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         40072
#define _APS_NEXT_CONTROL_VALUE         1144
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
